global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Use the http_2xx module from blackbox.yml
      timeout: [10s]
      
    static_configs:
      - targets:
          - https://github.com
          - https://stackoverflow.com
          - https://kubernetes.io
          - https://www.redhat.com

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115  # Replace with the actual DNS name or IP of your blackbox exporter

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
